# Generated by Django 5.2.17 on 2026-10-04 14:25

from django.db import migrations, models


def promote_existing_admins(apps, schema_editor):
    User = apps.get_model('accounts', 'User')
    User.objects.filter(is_platform_admin=True).update(is_platform_superadmin=True)


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_user_is_platform_admin'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_platform_superadmin',
            field=models.BooleanField(default=False),
        ),
        migrations.RunPython(promote_existing_admins, migrations.RunPython.noop),
    ]
