# Generated by Django 5.2.17 on 2026-10-05 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_platform_superadmin'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_service_admin',
            field=models.BooleanField(default=False),
        ),
    ]
