# Generated by Django 5.2.15 on 2026-07-03 14:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('orders', '0014_exchangerequest'),
        ('products', '0009_alter_stockmovement_reason'),
        ('stores', '0006_storesettings_risk_period_days_and_more'),
        ('team', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CommissionEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('dropshipper', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='commission_entries', to='team.teammember')),
                ('order_item', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='commission_entry', to='orders.orderitem')),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='products.product')),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='commission_entries', to='stores.store')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CommissionPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('note', models.TextField(blank=True)),
                ('paid_at', models.DateTimeField(auto_now_add=True)),
                ('dropshipper', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='commission_payments', to='team.teammember')),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='commission_payments', to='stores.store')),
            ],
            options={
                'ordering': ['-paid_at'],
            },
        ),
        migrations.CreateModel(
            name='Commission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('commission_type', models.CharField(choices=[('percentage', 'Pourcentage'), ('fixed', 'Montant fixe')], default='percentage', max_length=20)),
                ('value', models.DecimalField(decimal_places=2, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('dropshipper', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='commissions', to='team.teammember')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='commissions', to='products.product')),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='commissions', to='stores.store')),
            ],
            options={
                'ordering': ['-created_at'],
                'unique_together': {('dropshipper', 'product')},
            },
        ),
        migrations.CreateModel(
            name='DropshipperProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('dropshipper', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='selected_products', to='team.teammember')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dropshipper_selections', to='products.product')),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dropshipper_products', to='stores.store')),
            ],
            options={
                'ordering': ['-created_at'],
                'unique_together': {('dropshipper', 'product')},
            },
        ),
    ]
