# Generated by Django 5.2.16 on 2026-08-12 22:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('stores', '0011_store_meta_description_store_meta_title_and_more'),
        ('team', '0003_teammemberpermission'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('order', 'Commande'), ('complaint', 'Réclamation'), ('exchange', 'Échange'), ('cancellation', 'Annulation'), ('delivery', 'Livraison'), ('payment', 'Paiement'), ('stock', 'Stock'), ('webhook', 'Webhook'), ('review', 'Avis client'), ('quota', 'Quota / abonnement'), ('risk', 'Client à risque')], max_length=20)),
                ('level', models.CharField(choices=[('info', 'Info'), ('warning', 'Avertissement'), ('danger', 'Critique')], default='info', max_length=10)),
                ('title', models.CharField(max_length=200)),
                ('body', models.TextField(blank=True)),
                ('link', models.CharField(blank=True, help_text='Chemin relatif dans le dashboard, ex: /dashboard/commandes/56', max_length=255)),
                ('permission', models.CharField(blank=True, help_text="Clé du PERMISSION_CATALOG requise pour voir cette notification — vide = visible par toute l'équipe", max_length=50)),
                ('dedupe_key', models.CharField(blank=True, help_text="Empêche la commande evaluate_alerts de recréer la même alerte à chaque passage — vide pour les notifications d'événement (toujours uniques)", max_length=100)),
                ('is_read', models.BooleanField(default=False)),
                ('read_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='stores.store')),
                ('target_member', models.ForeignKey(blank=True, help_text="Notification personnelle (ex: commande qui vient de m'être assignée) — prioritaire sur `permission`", null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='team.teammember')),
            ],
            options={
                'ordering': ['-created_at'],
                'constraints': [models.UniqueConstraint(condition=models.Q(('dedupe_key', ''), _negated=True), fields=('store', 'dedupe_key'), name='unique_dedupe_key_per_store')],
            },
        ),
    ]
