# Generated by Django 5.2.15 on 2026-07-01 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_add_assignment_call_failure'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='payment_method',
            field=models.CharField(choices=[('cod', 'Paiement à la livraison'), ('chargily', 'Paiement en ligne (Chargily)')], default='cod', max_length=20),
        ),
    ]
