# Generated by Django 5.2.15 on 2026-07-01 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_order_payment_method'),
    ]

    operations = [
        migrations.AddField(
            model_name='callattempt',
            name='attempt_number',
            field=models.PositiveSmallIntegerField(default=1),
        ),
    ]
