# Generated by Django 5.2.15 on 2026-07-02 10:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0006_alter_order_status_alter_orderstatushistory_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='chargily_checkout_id',
            field=models.CharField(blank=True, db_index=True, max_length=100),
        ),
        migrations.AddField(
            model_name='order',
            name='chargily_payment_link',
            field=models.URLField(blank=True),
        ),
        migrations.CreateModel(
            name='PaymentWebhookLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(blank=True, max_length=50)),
                ('checkout_id', models.CharField(blank=True, max_length=100)),
                ('raw_payload', models.JSONField(default=dict)),
                ('signature_valid', models.BooleanField(default=False)),
                ('status', models.CharField(choices=[('received', 'Reçu'), ('processed', 'Traité'), ('error', 'Erreur')], default='received', max_length=20)),
                ('error_message', models.TextField(blank=True)),
                ('received_at', models.DateTimeField(auto_now_add=True)),
                ('order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='webhook_logs', to='orders.order')),
            ],
            options={
                'ordering': ['-received_at'],
            },
        ),
    ]
