# Generated by Django 5.2.15 on 2026-07-02 22:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0008_order_customer_email_abandonedcart'),
        ('stores', '0005_storesettings_menu_items_mediafolder_mediafile_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='carrier_shipment_created_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='carrier_status',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='order',
            name='carrier_tracking_number',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.CreateModel(
            name='CarrierAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('carrier', models.CharField(choices=[('yalidine', 'Yalidine'), ('zr_express', 'ZR Express')], max_length=20)),
                ('api_id', models.CharField(blank=True, max_length=100)),
                ('api_token', models.CharField(blank=True, max_length=200)),
                ('is_active', models.BooleanField(default=True)),
                ('is_default', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='carrier_accounts', to='stores.store')),
            ],
            options={
                'ordering': ['carrier'],
                'unique_together': {('store', 'carrier')},
            },
        ),
        migrations.AddField(
            model_name='order',
            name='carrier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='shipments', to='orders.carrieraccount'),
        ),
    ]
