# Generated by Django 5.2.15 on 2026-07-03 04:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0009_order_carrier_shipment_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='carrieraccount',
            name='departure_wilaya',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='carrieraccount',
            name='name',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
