# Generated by Django 5.2.15 on 2026-07-03 11:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0011_order_discount_amount_order_promo_code'),
        ('stores', '0006_storesettings_risk_period_days_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlacklistedPhone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(max_length=30)),
                ('message', models.TextField(blank=True)),
                ('blocked_attempts', models.PositiveIntegerField(default=0)),
                ('last_attempt_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blacklisted_phones', to='stores.store')),
            ],
            options={
                'ordering': ['-created_at'],
                'constraints': [models.UniqueConstraint(fields=('store', 'phone'), name='unique_store_blacklist_phone')],
            },
        ),
        migrations.CreateModel(
            name='CustomerRisk',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(max_length=30)),
                ('manual_risk', models.BooleanField(default=False)),
                ('note', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='customer_risks', to='stores.store')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('store', 'phone'), name='unique_store_customer_risk')],
            },
        ),
    ]
