# Generated by Django 5.2.15 on 2026-07-03 12:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0013_complaint_complaintmessage'),
        ('products', '0007_promotion'),
        ('stores', '0006_storesettings_risk_period_days_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExchangeRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.TextField()),
                ('status', models.CharField(choices=[('open', 'En attente'), ('approved', 'Approuvé'), ('rejected', 'Refusé')], default='open', max_length=20)),
                ('vendor_note', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('order_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exchange_requests', to='orders.orderitem')),
                ('replacement_option', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exchange_requests', to='products.variantoption')),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exchange_requests', to='stores.store')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
