# Generated by Django 5.2.15 on 2026-07-03 14:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0014_exchangerequest'),
        ('team', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='dropshipper',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dropshipper_orders', to='team.teammember'),
        ),
    ]
