# Generated by Django 5.2.15 on 2026-07-06 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0015_order_dropshipper'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='external_ref',
            field=models.CharField(blank=True, db_index=True, help_text="Identifiant de la commande sur un canal externe (ex: 'shopify:123456') — garantit l'idempotence des imports webhook", max_length=100),
        ),
    ]
