# Generated by Django 5.2.15 on 2026-07-07 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0016_order_external_ref'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carrieraccount',
            name='carrier',
            field=models.CharField(choices=[('yalidine', 'Yalidine'), ('zr_express', 'ZR Express'), ('noest', 'Noest'), ('guepex', 'Guepex'), ('maystro', 'Maystro')], max_length=20),
        ),
    ]
