# Generated by Django 5.2.15 on 2026-07-07 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0017_alter_carrieraccount_carrier'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carrieraccount',
            name='carrier',
            field=models.CharField(choices=[('yalidine', 'Yalidine'), ('zr_express', 'ZR Express'), ('noest', 'Noest'), ('guepex', 'Guepex'), ('maystro', 'Maystro'), ('waslet', 'Waslet'), ('imir', 'Imir'), ('dhd', 'DHD'), ('speedmail', 'SpeedMail'), ('worldexpress', 'Worldexpress'), ('ups', 'UPS'), ('anderson', 'Anderson'), ('ontime', 'OnTime'), ('yalitec', 'Yalitec'), ('assil_delivery', 'Assil Delivery'), ('zimou_express', 'Zimou Express'), ('tikjdadelivery', 'Tikjdadelivery'), ('ecomdz', 'EcomDz'), ('colireli', 'Colireli'), ('overed', 'Overed'), ('expediachrono', 'Expediachrono'), ('navex', 'Navex'), ('courier48hr', '48HR Courrier Express'), ('pachers', 'Pachers'), ('lynx', 'Lynx'), ('tls', 'TLS'), ('siexpress', 'Siexpress'), ('chronorex', 'Chronorex'), ('mdm', 'MDM')], max_length=20),
        ),
    ]
