# Generated by Django 5.2.15 on 2026-07-07 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0018_alter_carrieraccount_carrier'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='scheduled_at',
            field=models.DateTimeField(blank=True, help_text="Date/heure à laquelle une commande 'scheduled' doit être activée automatiquement (voir management command activate_scheduled_orders)", null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('scheduled', 'Programmée'), ('pending', 'En attente de confirmation'), ('no_answer_1', 'Non joignable — 1ère tentative'), ('no_answer_2', 'Non joignable — 2ème tentative'), ('no_answer_3', 'Non joignable — 3ème tentative'), ('confirmed', 'Confirmée'), ('shipped', 'Expédiée'), ('delivered', 'Livrée'), ('returned', 'Retournée'), ('cancel_requested', "Demande d'annulation"), ('cancelled', 'Annulée')], default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='orderstatushistory',
            name='status',
            field=models.CharField(choices=[('scheduled', 'Programmée'), ('pending', 'En attente de confirmation'), ('no_answer_1', 'Non joignable — 1ère tentative'), ('no_answer_2', 'Non joignable — 2ème tentative'), ('no_answer_3', 'Non joignable — 3ème tentative'), ('confirmed', 'Confirmée'), ('shipped', 'Expédiée'), ('delivered', 'Livrée'), ('returned', 'Retournée'), ('cancel_requested', "Demande d'annulation"), ('cancelled', 'Annulée')], max_length=20),
        ),
    ]
