# Generated by Django 5.2.15 on 2026-07-21 19:14

import core.validators
import orders.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0020_complaintmessage_attachment_complaintassignment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='complaintmessage',
            name='attachment',
            field=models.ImageField(blank=True, null=True, upload_to=orders.models.complaint_attachment_path, validators=[core.validators.validate_image_extension, core.validators.validate_image_size]),
        ),
    ]
