# Generated by Django 5.2.16 on 2026-08-11 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0021_alter_complaintmessage_attachment'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='stop_desk',
            field=models.BooleanField(default=False, help_text="Livraison en point relais (True) plutôt qu'à domicile (False) — affecte le tarif transporteur et le mode d'expédition envoyé à l'API"),
        ),
    ]
