# Generated by Django 5.2.16 on 2026-08-11 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0022_order_stop_desk'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='station_code',
            field=models.CharField(blank=True, help_text='Code du bureau/point relais choisi (requis par certains transporteurs, ex: Noest, quand stop_desk=True)', max_length=20),
        ),
    ]
