# Generated by Django 5.2.16 on 2026-08-12 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0023_order_station_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('scheduled', 'Programmée'), ('pending', 'En attente de confirmation'), ('no_answer_1', 'Non joignable — 1ère tentative'), ('no_answer_2', 'Non joignable — 2ème tentative'), ('no_answer_3', 'Non joignable — 3ème tentative'), ('no_answer', 'Sans réponse'), ('confirmed', 'Confirmée'), ('preparing', 'Préparation de commande'), ('prepared', 'Préparée'), ('in_progress', 'En cours'), ('shipped', 'Expédiée'), ('out_for_delivery', 'Sorti en livraison'), ('delivered', 'Livrée'), ('returned', 'Retournée'), ('cancel_requested', "Demande d'annulation"), ('cancelled', 'Annulée'), ('duplicate', 'Commande double'), ('fake', 'Commande fictive')], default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='orderstatushistory',
            name='status',
            field=models.CharField(choices=[('scheduled', 'Programmée'), ('pending', 'En attente de confirmation'), ('no_answer_1', 'Non joignable — 1ère tentative'), ('no_answer_2', 'Non joignable — 2ème tentative'), ('no_answer_3', 'Non joignable — 3ème tentative'), ('no_answer', 'Sans réponse'), ('confirmed', 'Confirmée'), ('preparing', 'Préparation de commande'), ('prepared', 'Préparée'), ('in_progress', 'En cours'), ('shipped', 'Expédiée'), ('out_for_delivery', 'Sorti en livraison'), ('delivered', 'Livrée'), ('returned', 'Retournée'), ('cancel_requested', "Demande d'annulation"), ('cancelled', 'Annulée'), ('duplicate', 'Commande double'), ('fake', 'Commande fictive')], max_length=20),
        ),
    ]
