# Generated by Django 5.2.16 on 2026-08-12 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0024_alter_order_status_alter_orderstatushistory_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='carrieraccount',
            name='webhook_secret',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
