# Generated by Django 5.2.16 on 2026-08-12 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0025_carrieraccount_webhook_secret'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='tracking_substatus',
            field=models.CharField(blank=True, choices=[('pending_processing', 'En attente de traitement'), ('accepted', 'Accepté'), ('cancelled', 'Annulé'), ('unreachable', 'Injoignable')], help_text='Tag de triage manuel posé par le confirmateur sur une commande en cours de livraison — indépendant du statut brut du transporteur', max_length=20),
        ),
    ]
