# Generated by Django 5.2.16 on 2026-08-12 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0026_order_tracking_substatus'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='label_generated_at',
            field=models.DateTimeField(blank=True, help_text="Renseigné automatiquement la première fois que l'étiquette PDF de cette commande est téléchargée/générée", null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='label_printed_at',
            field=models.DateTimeField(blank=True, help_text='Renseigné quand le vendeur marque le ticket comme physiquement imprimé (pipeline Expéditions & Retours)', null=True),
        ),
    ]
