# Generated by Django 5.2.16 on 2026-08-12 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0027_order_label_generated_at_order_label_printed_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='prepared_at',
            field=models.DateTimeField(blank=True, help_text='Renseigné quand le colis a été physiquement préparé/emballé, avant remise au transporteur', null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='return_validated_at',
            field=models.DateTimeField(blank=True, help_text='Renseigné quand le vendeur confirme avoir physiquement reçu et vérifié un colis retourné', null=True),
        ),
    ]
