# Generated by Django 5.2.16 on 2026-08-12 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0028_order_prepared_at_order_return_validated_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='restocked_at',
            field=models.DateTimeField(blank=True, help_text="Renseigné dès que les articles de cette commande ont été remis en stock (retour validé ou annulation) — garde d'idempotence, évite un double restockage", null=True),
        ),
    ]
