# Generated by Django 5.2.16 on 2026-08-12 22:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inbox', '0001_initial'),
        ('orders', '0029_order_restocked_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='exchangerequest',
            name='conversation',
            field=models.OneToOneField(blank=True, help_text="Fil de discussion de la boîte de réception unifiée (2026-08) — le reason du client et le vendor_note d'approbation y apparaissent comme messages", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='exchange_request', to='inbox.conversation'),
        ),
    ]
