# Generated by Django 5.2.16 on 2026-08-12 22:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0030_exchangerequest_conversation'),
        ('stores', '0011_store_meta_description_store_meta_title_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CommuneRate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wilaya_id', models.PositiveSmallIntegerField()),
                ('commune_name', models.CharField(max_length=100)),
                ('home_price', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('desk_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='commune_rates', to='stores.store')),
            ],
            options={
                'ordering': ['commune_name'],
                'unique_together': {('store', 'wilaya_id', 'commune_name')},
            },
        ),
        migrations.CreateModel(
            name='WilayaRate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wilaya_id', models.PositiveSmallIntegerField()),
                ('wilaya_name', models.CharField(max_length=100)),
                ('home_price', models.DecimalField(decimal_places=2, default=0, help_text='Frais de livraison à domicile', max_digits=10)),
                ('desk_price', models.DecimalField(blank=True, decimal_places=2, help_text='Frais de livraison au bureau/point relais — vide si non proposé', max_digits=10, null=True)),
                ('show_home', models.BooleanField(default=True)),
                ('show_desk', models.BooleanField(default=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wilaya_rates', to='stores.store')),
            ],
            options={
                'ordering': ['wilaya_id'],
                'unique_together': {('store', 'wilaya_id')},
            },
        ),
    ]
