# Generated by Django 5.2.16 on 2026-08-13 17:36

from django.db import migrations, models


def migrate_delivery_type_forward(apps, schema_editor):
    Order = apps.get_model('orders', 'Order')
    for order in Order.objects.exclude(delivery_type='').only('id', 'delivery_type', 'delivery_types'):
        order.delivery_types = [order.delivery_type]
        order.save(update_fields=['delivery_types'])


def migrate_delivery_type_backward(apps, schema_editor):
    Order = apps.get_model('orders', 'Order')
    for order in Order.objects.exclude(delivery_types=[]).only('id', 'delivery_type', 'delivery_types'):
        if order.delivery_types:
            order.delivery_type = order.delivery_types[0]
            order.save(update_fields=['delivery_type'])


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0031_communerate_wilayarate'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='delivery_types',
            field=models.JSONField(blank=True, default=list, help_text='Liste de codes DELIVERY_CHOICES — plusieurs types combinables (ex: Assurance + Échange)'),
        ),
        migrations.RunPython(migrate_delivery_type_forward, migrate_delivery_type_backward),
        migrations.RemoveField(
            model_name='order',
            name='delivery_type',
        ),
    ]
