# Generated by Django 5.2.16 on 2026-08-13 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0032_remove_order_delivery_type_order_delivery_types'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='stock_deducted_at',
            field=models.DateTimeField(blank=True, help_text="Renseigné dès que le stock a été décrémenté pour cette commande — garde d'idempotence quand StoreSettings.deduct_stock_on_order_create est désactivé (déduction différée à la confirmation)", null=True),
        ),
    ]
