# Generated by Django 5.2.16 on 2026-08-13 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0033_order_stock_deducted_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='payment_collected_amount',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Montant effectivement reçu du transporteur — peut différer de `total` (écart de versement), sert la vérification de cohérence', max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='payment_collected_at',
            field=models.DateTimeField(blank=True, help_text='Renseigné quand le vendeur pointe avoir reçu le versement COD du transporteur pour cette commande livrée (page Paiements — « Paiement récupéré »)', null=True),
        ),
    ]
