# Generated by Django 5.2.16 on 2026-08-13 21:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0034_order_payment_collected_amount_and_more'),
        ('stores', '0013_store_currency_store_currency_symbol_and_more'),
        ('team', '0003_teammemberpermission'),
    ]

    operations = [
        migrations.CreateModel(
            name='DispatchRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('match_type', models.CharField(choices=[('product', 'Par produit'), ('wilaya', 'Par wilaya')], max_length=10)),
                ('match_value', models.CharField(help_text='Nom de produit (recherche partielle) ou nom de wilaya exact selon match_type', max_length=100)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('carrier', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dispatch_rules', to='orders.carrieraccount')),
                ('confirmateur', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dispatch_rules', to='team.teammember')),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dispatch_rules', to='stores.store')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
    ]
