# Generated by Django 5.2.16 on 2026-08-14 13:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0035_dispatchrule'),
        ('products', '0017_stockmovement_variant_sub_option'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='variant_sub_option',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='products.variantsuboption'),
        ),
    ]
