# Generated by Django 5.2.16 on 2026-09-04 14:55

import core.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0036_orderitem_variant_sub_option'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carrieraccount',
            name='api_token',
            field=core.fields.EncryptedTextField(blank=True),
        ),
        migrations.AlterField(
            model_name='carrieraccount',
            name='webhook_secret',
            field=core.fields.EncryptedTextField(blank=True),
        ),
    ]
