# Generated by Django 5.2.17 on 2026-09-05 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0038_encrypt_existing_secrets'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='risk_explanation',
            field=models.TextField(blank=True, help_text="Explication en langage naturel générée par l'IA à la demande — mise en cache une fois générée, jamais régénérée automatiquement"),
        ),
        migrations.AddField(
            model_name='order',
            name='risk_score',
            field=models.PositiveSmallIntegerField(blank=True, help_text='Score de risque déterministe 0-100 calculé à la création — null pour les commandes antérieures à cette fonctionnalité', null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='risk_signals',
            field=models.JSONField(blank=True, default=list, help_text='Codes des signaux déclenchés (cancel_return_rate, unusual_frequency, unusual_amount, location_mismatch)'),
        ),
    ]
