# Generated by Django 5.2.17 on 2026-09-10 21:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0039_order_risk_explanation_order_risk_score_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carrieraccount',
            name='carrier',
            field=models.CharField(choices=[('yalidine', 'Yalidine'), ('zr_express', 'ZR Express'), ('noest', 'Noest'), ('guepex', 'Guepex'), ('maystro', 'Maystro'), ('imir', 'Imir'), ('dhd', 'DHD'), ('speedmail', 'SpeedMail'), ('worldexpress', 'Worldexpress'), ('ups', 'UPS'), ('anderson', 'Anderson'), ('ontime', 'OnTime'), ('yalitec', 'Yalitec'), ('assil_delivery', 'Assil Delivery'), ('zimou_express', 'Zimou Express'), ('tikjdadelivery', 'Tikjdadelivery'), ('ecomdz', 'EcomDz'), ('colireli', 'Colireli'), ('expediachrono', 'Expediachrono'), ('navex', 'Navex'), ('courier48hr', '48HR Courrier Express'), ('pachers', 'Pachers'), ('lynx', 'Lynx'), ('tls', 'TLS'), ('siexpress', 'Siexpress'), ('chronorex', 'Chronorex'), ('mdm', 'MDM'), ('colivraison', 'Colivraison'), ('elogistia', 'Elogistia'), ('near_delivery', 'Near Delivery'), ('easy_speed', 'Easy & Speed'), ('economiqua', 'Economiqua'), ('wecan', 'We Can Services'), ('speeddelivery', 'Speed Delivery'), ('gsecommerce', 'GS Ecommerce')], max_length=20),
        ),
    ]
