# Generated by Django 5.2.17 on 2026-09-05 17:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_assistant', '0001_initial'),
        ('stores', '0018_encrypt_existing_secrets'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='aiconversation',
            name='session_id',
            field=models.CharField(blank=True, db_index=True, max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='aiconversation',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ai_conversations', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddConstraint(
            model_name='aiconversation',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('user__isnull', False), ('session_id__isnull', True)), models.Q(('user__isnull', True), ('session_id__isnull', False)), _connector='OR'), name='ai_conversation_user_xor_session'),
        ),
    ]
