# Generated by Django 5.2.17 on 2026-09-11 21:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_assistant', '0002_aiconversation_session_id_alter_aiconversation_user_and_more'),
        ('products', '0021_backfill_product_slug'),
        ('stores', '0019_storeaudit'),
    ]

    operations = [
        migrations.CreateModel(
            name='AIPendingAction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tool_name', models.CharField(max_length=60)),
                ('summary', models.CharField(max_length=300)),
                ('payload', models.JSONField(default=list)),
                ('target_ids', models.JSONField(default=list)),
                ('status', models.CharField(choices=[('pending', 'pending'), ('confirmed', 'confirmed'), ('rejected', 'rejected'), ('expired', 'expired')], default='pending', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField()),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('conversation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pending_actions', to='ai_assistant.aiconversation')),
            ],
        ),
        migrations.AddField(
            model_name='aimessage',
            name='pending_action',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='messages', to='ai_assistant.aipendingaction'),
        ),
        migrations.CreateModel(
            name='AIProductDraft',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(choices=[('photo', 'photo'), ('invoice', 'invoice'), ('chat_text', 'chat_text')], max_length=10)),
                ('source_image', models.ImageField(blank=True, null=True, upload_to='ai_drafts/')),
                ('extracted_data', models.JSONField(default=dict)),
                ('status', models.CharField(choices=[('pending_review', 'pending_review'), ('created', 'created'), ('discarded', 'discarded')], default='pending_review', max_length=15)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='products.product')),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ai_product_drafts', to='stores.store')),
            ],
        ),
    ]
