# Generated by Django 5.2.17 on 2026-10-05 11:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_assistant', '0003_aipendingaction_aimessage_pending_action_and_more'),
        ('stores', '0023_modules'),
    ]

    operations = [
        migrations.CreateModel(
            name='AIUsageDay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.DateField()),
                ('calls', models.PositiveIntegerField(default=0)),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ai_usage', to='stores.store')),
            ],
            options={
                'unique_together': {('store', 'day')},
            },
        ),
    ]
