# Generated by Django 5.2.17 on 2026-10-05 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_assistant', '0004_modules'),
        ('stores', '0026_ai_quotas'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='aiusageday',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='aiusageday',
            name='feature',
            field=models.CharField(blank=True, default='', max_length=30),
        ),
        migrations.AlterUniqueTogether(
            name='aiusageday',
            unique_together={('store', 'day', 'feature')},
        ),
    ]
