# Generated by Django 5.2.15 on 2026-06-29 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_supplier_credit_payment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productreview',
            old_name='client_name',
            new_name='first_name',
        ),
        migrations.AddField(
            model_name='productreview',
            name='email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name='productreview',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='reviews/'),
        ),
        migrations.AddField(
            model_name='productreview',
            name='last_name',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
