# Generated by Django 5.2.15 on 2026-07-03 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_stockmovement'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stockmovement',
            name='reason',
            field=models.CharField(choices=[('exchange_return', 'Retour échange'), ('exchange_issue', 'Sortie échange'), ('order_sale', 'Vente (commande)')], max_length=30),
        ),
    ]
