# Generated by Django 5.2.15 on 2026-07-03 18:54

import core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0009_alter_stockmovement_reason'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='categories/', validators=[core.validators.validate_image_extension, core.validators.validate_image_size]),
        ),
        migrations.AlterField(
            model_name='productimage',
            name='image',
            field=models.ImageField(upload_to='products/', validators=[core.validators.validate_image_extension, core.validators.validate_image_size]),
        ),
        migrations.AlterField(
            model_name='productreview',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='reviews/', validators=[core.validators.validate_image_extension, core.validators.validate_image_size]),
        ),
        migrations.AlterField(
            model_name='variantoption',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='variants/', validators=[core.validators.validate_image_extension, core.validators.validate_image_size]),
        ),
    ]
