# Generated by Django 5.2.15 on 2026-07-21 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0010_alter_category_image_alter_productimage_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='meta_description',
            field=models.CharField(blank=True, help_text='Balise <meta name="description"> — retombe sur un extrait de la description si vide', max_length=160),
        ),
        migrations.AddField(
            model_name='product',
            name='meta_title',
            field=models.CharField(blank=True, help_text='Balise <title> de la fiche produit publique — retombe sur le nom du produit si vide', max_length=70),
        ),
    ]
