# Generated by Django 5.2.16 on 2026-08-05 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0011_product_meta_description_product_meta_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stockmovement',
            name='reason',
            field=models.CharField(choices=[('exchange_return', 'Retour échange'), ('exchange_issue', 'Sortie échange'), ('order_sale', 'Vente (commande)'), ('manual_adjustment', 'Ajustement manuel')], max_length=30),
        ),
    ]
