# Generated by Django 5.2.16 on 2026-08-12 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0012_alter_stockmovement_reason'),
    ]

    operations = [
        migrations.AddField(
            model_name='stockmovement',
            name='stock_after',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='stockmovement',
            name='stock_before',
            field=models.IntegerField(blank=True, help_text="Stock juste avant ce mouvement — null pour l'historique antérieur au chantier 2026-08 (aucun instantané passé disponible)", null=True),
        ),
        migrations.AlterField(
            model_name='stockmovement',
            name='reason',
            field=models.CharField(choices=[('exchange_return', 'Retour échange'), ('exchange_issue', 'Sortie échange'), ('order_sale', 'Vente (commande)'), ('manual_adjustment', 'Ajustement manuel'), ('order_return', 'Retour commande'), ('order_cancelled', 'Annulation commande')], max_length=30),
        ),
    ]
