# Generated by Django 5.2.16 on 2026-08-13 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0013_stockmovement_stock_after_stockmovement_stock_before_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='stockmovement',
            name='batch_id',
            field=models.UUIDField(blank=True, db_index=True, help_text='Regroupe les mouvements créés par une même sauvegarde produit (plusieurs variantes modifiées en une fois) — voir StockMovementListView, qui les affiche comme une seule ligne avec détail dépliable', null=True),
        ),
    ]
