# Generated by Django 5.2.16 on 2026-08-14 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0014_stockmovement_batch_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='dropshipping_price',
            field=models.DecimalField(blank=True, decimal_places=2, help_text="Prix « coûtant » facturé au dropshipper — sa marge = prix de vente qu'il choisit moins ce prix", max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='minimum_selling_price',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Prix plancher que le dropshipper doit respecter en revendant ce produit', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='offer_enabled',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='product',
            name='offer_price',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Prix total facturé pour ce palier de quantité', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='offer_quantity',
            field=models.PositiveIntegerField(blank=True, help_text="Nombre d'unités du palier (ex: 2)", null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='specific_shipping_desk_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='specific_shipping_enabled',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='product',
            name='specific_shipping_home_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
