# Generated by Django 5.2.16 on 2026-08-14 13:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0015_product_dropshipping_price_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='VariantSubOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=100)),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('cost_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('stock', models.PositiveIntegerField(default=0)),
                ('sku', models.CharField(blank=True, max_length=100)),
                ('dropshipping_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('minimum_selling_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('allow_out_of_stock', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('order', models.PositiveSmallIntegerField(default=0)),
                ('option', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sub_options', to='products.variantoption')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
    ]
