# Generated by Django 5.2.16 on 2026-08-14 13:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0016_variantsuboption'),
    ]

    operations = [
        migrations.AddField(
            model_name='stockmovement',
            name='variant_sub_option',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stock_movements', to='products.variantsuboption'),
        ),
    ]
