# Generated by Django 5.2.16 on 2026-08-14 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0017_stockmovement_variant_sub_option'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='countdown_end',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='has_position',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='product',
            name='position_range',
            field=models.CharField(blank=True, help_text='Ex: allée/rayon', max_length=50),
        ),
        migrations.AddField(
            model_name='product',
            name='position_slot',
            field=models.CharField(blank=True, help_text='Ex: emplacement précis', max_length=50),
        ),
        migrations.AddField(
            model_name='product',
            name='position_stage',
            field=models.CharField(blank=True, help_text='Ex: étage/niveau', max_length=50),
        ),
        migrations.AddField(
            model_name='product',
            name='show_countdown',
            field=models.BooleanField(default=False, help_text="Affiche un compte à rebours jusqu'à countdown_end sur la fiche produit publique"),
        ),
        migrations.AddField(
            model_name='product',
            name='show_discounted_price',
            field=models.BooleanField(default=True, help_text='Afficher le prix réduit — si désactivé avec show_full_price actif, seul le prix plein est visible'),
        ),
        migrations.AddField(
            model_name='product',
            name='show_full_price',
            field=models.BooleanField(default=True, help_text="Afficher le prix hors remise (barré) quand une réduction s'applique"),
        ),
        migrations.AddField(
            model_name='product',
            name='show_images',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='product',
            name='show_title',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='product',
            name='stock_alert_1',
            field=models.PositiveIntegerField(blank=True, help_text="Seuil d'alerte stock faible (remplace le seuil global de la boutique pour ce produit)", null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='stock_alert_2',
            field=models.PositiveIntegerField(blank=True, help_text="Seuil d'alerte stock très faible", null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='stock_alert_3',
            field=models.PositiveIntegerField(blank=True, help_text="Seuil d'alerte stock critique", null=True),
        ),
    ]
