# Generated by Django 5.2.16 on 2026-08-14 13:48

import core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0018_product_countdown_end_product_has_position_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='meta_keywords',
            field=models.CharField(blank=True, help_text='Mots-clés séparés par des virgules', max_length=255),
        ),
        migrations.AddField(
            model_name='product',
            name='meta_robots',
            field=models.CharField(blank=True, choices=[('index,follow', 'Indexer, suivre les liens (défaut)'), ('noindex,follow', 'Ne pas indexer, suivre les liens'), ('index,nofollow', 'Indexer, ne pas suivre les liens'), ('noindex,nofollow', 'Ne pas indexer, ne pas suivre les liens')], help_text='Balise <meta name="robots"> — vide = index,follow (comportement par défaut)', max_length=20),
        ),
        migrations.AddField(
            model_name='product',
            name='og_image',
            field=models.ImageField(blank=True, help_text='Image de partage Facebook/WhatsApp (Open Graph) — retombe sur la 1ère image du produit si vide', null=True, upload_to='products/seo/', validators=[core.validators.validate_image_extension, core.validators.validate_image_size]),
        ),
        migrations.AddField(
            model_name='product',
            name='twitter_image',
            field=models.ImageField(blank=True, help_text='Image de la carte Twitter — retombe sur og_image puis la 1ère image du produit si vide', null=True, upload_to='products/seo/', validators=[core.validators.validate_image_extension, core.validators.validate_image_size]),
        ),
    ]
