# Generated by Django 5.2.16 on 2026-09-04 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0019_product_meta_keywords_product_meta_robots_and_more'),
        ('stores', '0016_remove_storesettings_free_shipping_if_product_free_shipping'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='slug',
            field=models.SlugField(blank=True, help_text="Généré automatiquement depuis le nom — utilisé dans l'URL publique, l'ancienne URL par ID reste valide", max_length=220),
        ),
        migrations.AddConstraint(
            model_name='product',
            constraint=models.UniqueConstraint(condition=models.Q(('slug__gt', '')), fields=('store', 'slug'), name='unique_product_slug_per_store'),
        ),
    ]
