from django.urls import path
from .views import (
    OrderListCreateView, OrderDetailView,
    OrderStatusView, OrderRejectCancellationView, OrderStatsView, ConfirmationRateView,
    OrderAssignmentView,
    CallAttemptListView, CallAttemptDetailView,
    FailureReasonListView, FailureReasonDetailView,
    AbandonedCartListView, AbandonedCartRemindView,
    ClientListView, CustomerRiskToggleView,
    BlacklistListCreateView, BlacklistDetailView,
    ComplaintListView, ComplaintDetailView, ComplaintStatusView, ComplaintMessageCreateView, ComplaintAssignmentView,
    ExchangeListView, ExchangeDetailView, ExchangeStatusView,
)
from .stats_views import (
    OrdersStatsDetailView, ReturnsStatsView, FailureStatsView, StockSalesStatsView,
    ProductsStatsView, WilayaStatsView, SourceStatsView, GlobalStatsView,
)

urlpatterns = [
    path('abandoned-carts/',                       AbandonedCartListView.as_view()),
    path('abandoned-carts/<int:pk>/remind/',       AbandonedCartRemindView.as_view()),
    path('clients/',                              ClientListView.as_view()),
    path('clients/<str:phone>/risk/',             CustomerRiskToggleView.as_view()),
    path('blacklist/',                            BlacklistListCreateView.as_view()),
    path('blacklist/<int:pk>/',                   BlacklistDetailView.as_view()),
    path('complaints/',                           ComplaintListView.as_view()),
    path('complaints/<int:pk>/',                  ComplaintDetailView.as_view()),
    path('complaints/<int:pk>/status/',           ComplaintStatusView.as_view()),
    path('complaints/<int:pk>/messages/',         ComplaintMessageCreateView.as_view()),
    path('complaints/<int:pk>/assignment/',       ComplaintAssignmentView.as_view()),
    path('exchanges/',                            ExchangeListView.as_view()),
    path('exchanges/<int:pk>/',                   ExchangeDetailView.as_view()),
    path('exchanges/<int:pk>/status/',            ExchangeStatusView.as_view()),
    path('',                                      OrderListCreateView.as_view()),
    path('stats/',                                OrderStatsView.as_view()),
    path('stats/confirmation/',                   ConfirmationRateView.as_view()),
    path('stats/orders/',                         OrdersStatsDetailView.as_view()),
    path('stats/returns/',                        ReturnsStatsView.as_view()),
    path('stats/failures/',                       FailureStatsView.as_view()),
    path('stats/stock-sales/',                    StockSalesStatsView.as_view()),
    path('stats/products/',                       ProductsStatsView.as_view()),
    path('stats/wilayas/',                        WilayaStatsView.as_view()),
    path('stats/sources/',                        SourceStatsView.as_view()),
    path('stats/global/',                         GlobalStatsView.as_view()),
    path('failure-reasons/',                      FailureReasonListView.as_view()),
    path('failure-reasons/<int:pk>/',             FailureReasonDetailView.as_view()),
    path('<int:pk>/',                             OrderDetailView.as_view()),
    path('<int:pk>/status/',                      OrderStatusView.as_view()),
    path('<int:pk>/reject-cancellation/',          OrderRejectCancellationView.as_view()),
    path('<int:pk>/assignment/',                  OrderAssignmentView.as_view()),
    path('<int:pk>/call-attempts/',               CallAttemptListView.as_view()),
    path('<int:pk>/call-attempts/<int:cid>/',     CallAttemptDetailView.as_view()),
]
