from django.urls import path
from .views import (
    OrderListCreateView, OrderDetailView,
    OrderStatusView, OrderStatsView, ConfirmationRateView,
    OrderAssignmentView,
    CallAttemptListView, CallAttemptDetailView,
    FailureReasonListView, FailureReasonDetailView,
    AbandonedCartListView,
    ClientListView, CustomerRiskToggleView,
    BlacklistListCreateView, BlacklistDetailView,
    ComplaintListView, ComplaintDetailView, ComplaintStatusView, ComplaintMessageCreateView,
    ExchangeListView, ExchangeDetailView, ExchangeStatusView,
)

urlpatterns = [
    path('abandoned-carts/',                       AbandonedCartListView.as_view()),
    path('clients/',                              ClientListView.as_view()),
    path('clients/<str:phone>/risk/',             CustomerRiskToggleView.as_view()),
    path('blacklist/',                            BlacklistListCreateView.as_view()),
    path('blacklist/<int:pk>/',                   BlacklistDetailView.as_view()),
    path('complaints/',                           ComplaintListView.as_view()),
    path('complaints/<int:pk>/',                  ComplaintDetailView.as_view()),
    path('complaints/<int:pk>/status/',           ComplaintStatusView.as_view()),
    path('complaints/<int:pk>/messages/',         ComplaintMessageCreateView.as_view()),
    path('exchanges/',                            ExchangeListView.as_view()),
    path('exchanges/<int:pk>/',                   ExchangeDetailView.as_view()),
    path('exchanges/<int:pk>/status/',            ExchangeStatusView.as_view()),
    path('',                                      OrderListCreateView.as_view()),
    path('stats/',                                OrderStatsView.as_view()),
    path('stats/confirmation/',                   ConfirmationRateView.as_view()),
    path('failure-reasons/',                      FailureReasonListView.as_view()),
    path('failure-reasons/<int:pk>/',             FailureReasonDetailView.as_view()),
    path('<int:pk>/',                             OrderDetailView.as_view()),
    path('<int:pk>/status/',                      OrderStatusView.as_view()),
    path('<int:pk>/assignment/',                  OrderAssignmentView.as_view()),
    path('<int:pk>/call-attempts/',               CallAttemptListView.as_view()),
    path('<int:pk>/call-attempts/<int:cid>/',     CallAttemptDetailView.as_view()),
]
