# Generated by Django 5.2.15 on 2026-07-03 17:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('stores', '0006_storesettings_risk_period_days_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChannelConnection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('channel', models.CharField(choices=[('shopify', 'Shopify'), ('google_sheets', 'Google Sheets')], max_length=20)),
                ('shop_url', models.CharField(blank=True, help_text='Ex: monshop.myshopify.com, ou URL du Google Sheet', max_length=200)),
                ('api_key', models.CharField(blank=True, max_length=200)),
                ('api_secret', models.CharField(blank=True, max_length=200)),
                ('is_active', models.BooleanField(default=True)),
                ('connected_at', models.DateTimeField(auto_now_add=True)),
                ('last_synced_at', models.DateTimeField(blank=True, null=True)),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='channel_connections', to='stores.store')),
            ],
            options={
                'ordering': ['channel'],
                'unique_together': {('store', 'channel')},
            },
        ),
        migrations.CreateModel(
            name='ChannelSyncLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('channel', models.CharField(choices=[('shopify', 'Shopify'), ('google_sheets', 'Google Sheets')], max_length=20)),
                ('direction', models.CharField(choices=[('push', 'Push (MZSolutions → canal)'), ('pull', 'Pull (canal → MZSolutions)')], max_length=10)),
                ('status', models.CharField(choices=[('success', 'Succès'), ('error', 'Erreur')], max_length=10)),
                ('items_synced', models.PositiveIntegerField(default=0)),
                ('message', models.TextField(blank=True)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('connection', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='logs', to='channels.channelconnection')),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='channel_sync_logs', to='stores.store')),
            ],
            options={
                'ordering': ['-started_at'],
            },
        ),
    ]
