# Generated by Django 5.2.15 on 2026-07-06 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('channels', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='channelconnection',
            name='access_token',
            field=models.CharField(blank=True, help_text='Token OAuth obtenu après autorisation par le marchand (Shopify) — jamais renvoyé en clair au frontend', max_length=255),
        ),
        migrations.AddField(
            model_name='channelconnection',
            name='scope',
            field=models.CharField(blank=True, max_length=500),
        ),
    ]
