# Generated by Django 5.2.15 on 2026-07-06 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('channels', '0002_channelconnection_access_token_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='channelsynclog',
            name='direction',
            field=models.CharField(choices=[('push', 'Push (MZSolutions → canal)'), ('pull', 'Pull commandes (canal → MZSolutions)'), ('pull_products', 'Pull produits (canal → MZSolutions)')], max_length=20),
        ),
    ]
