# Generated by Django 5.2.16 on 2026-09-04 14:55

import core.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('channels', '0003_alter_channelsynclog_direction'),
    ]

    operations = [
        migrations.AlterField(
            model_name='channelconnection',
            name='access_token',
            field=core.fields.EncryptedTextField(blank=True, help_text='Token OAuth obtenu après autorisation par le marchand (Shopify) — jamais renvoyé en clair au frontend'),
        ),
        migrations.AlterField(
            model_name='channelconnection',
            name='api_secret',
            field=core.fields.EncryptedTextField(blank=True),
        ),
    ]
