# Generated by Django 5.2.16 on 2026-08-12 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cost',
            name='category',
            field=models.CharField(choices=[('operational', 'Opérationnel'), ('marketing', 'Marketing'), ('delivery_variance', 'Écarts de livraison'), ('confirmation_fees', 'Frais de confirmation'), ('return_cost', 'Coût de retour'), ('other_debts', 'Autres dettes')], max_length=20),
        ),
    ]
