# Generated by Django 5.2.17 on 2026-09-12 20:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0040_alter_carrieraccount_carrier'),
        ('platform_admin', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlatformOrderAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assigned_at', models.DateTimeField(auto_now_add=True)),
                ('confirmateur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_assignments', to='platform_admin.platformconfirmateur')),
                ('order', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='platform_assignment', to='orders.order')),
            ],
        ),
    ]
