# Generated by Django 5.2.17 on 2026-09-13 09:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('platform_admin', '0002_platformorderassignment'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlatformAssignmentPermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('permission', models.CharField(max_length=50)),
                ('enabled', models.BooleanField(default=True)),
                ('assignment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='permission_overrides', to='platform_admin.platformconfirmateurassignment')),
            ],
            options={
                'unique_together': {('assignment', 'permission')},
            },
        ),
    ]
