# Generated by Django 5.2.17 on 2026-10-04 21:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('platform_admin', '0003_platformassignmentpermission'),
    ]

    operations = [
        migrations.CreateModel(
            name='ErrorEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fingerprint', models.CharField(max_length=40, unique=True)),
                ('exception_type', models.CharField(max_length=120)),
                ('route', models.CharField(max_length=200)),
                ('method', models.CharField(max_length=10)),
                ('location', models.CharField(blank=True, max_length=300)),
                ('count', models.PositiveIntegerField(default=1)),
                ('status', models.CharField(choices=[('open', 'Ouverte'), ('resolved', 'Résolue')], default='open', max_length=10)),
                ('first_seen', models.DateTimeField(auto_now_add=True)),
                ('last_seen', models.DateTimeField()),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-last_seen'],
            },
        ),
        migrations.CreateModel(
            name='PlatformSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trial_days', models.PositiveIntegerField(default=30, help_text="Durée de l'essai gratuit des NOUVELLES boutiques")),
                ('allow_registration', models.BooleanField(default=True, help_text='False = inscriptions fermées (incident, maintenance)')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
