# Generated by Django 5.2.17 on 2026-10-04 21:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('platform_admin', '0004_system_models'),
        ('stores', '0022_subscriptionpayment_refund'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=120)),
                ('body', models.TextField(max_length=2000)),
                ('status', models.CharField(choices=[('new', 'Nouveau'), ('read', 'Lu'), ('handled', 'Traité')], default='new', max_length=8)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contact_messages', to='stores.store')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PlatformAnnouncement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120)),
                ('body', models.TextField(max_length=1000)),
                ('audience', models.CharField(choices=[('all', 'Tous les vendeurs'), ('trial', 'En essai'), ('subscribed', 'Abonnés'), ('expired', 'Essai ou abonnement expiré')], default='all', max_length=12)),
                ('level', models.CharField(choices=[('info', 'Information'), ('warning', 'Avertissement')], default='info', max_length=10)),
                ('is_active', models.BooleanField(default=True)),
                ('ends_at', models.DateTimeField(blank=True, null=True)),
                ('emailed_count', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
