# Generated by Django 5.2.17 on 2026-10-05 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('platform_admin', '0005_communication'),
    ]

    operations = [
        migrations.CreateModel(
            name='TaskRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60, unique=True)),
                ('last_started_at', models.DateTimeField(blank=True, null=True)),
                ('last_finished_at', models.DateTimeField(blank=True, null=True)),
                ('last_status', models.CharField(choices=[('running', 'En cours'), ('ok', 'Réussie'), ('error', 'En erreur')], default='ok', max_length=10)),
                ('last_message', models.CharField(blank=True, max_length=300)),
                ('runs_count', models.PositiveIntegerField(default=0)),
            ],
        ),
    ]
