# Generated by Django 5.2.17 on 2026-10-05 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('platform_admin', '0006_taskrun'),
    ]

    operations = [
        migrations.AddField(
            model_name='platformsettings',
            name='ai_daily_limit',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='platformsettings',
            name='disabled_features',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
