# Generated by Django 5.2.17 on 2026-10-05 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('platform_admin', '0008_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='platformsettings',
            name='ai_weekly_limit',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
