# Generated by Django 5.2.17 on 2026-10-09 14:04

import django.db.models.deletion
import platform_admin.dispatch_models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0041_chargily_to_sofizpay'),
        ('platform_admin', '0010_ai_quotas'),
        ('stores', '0026_ai_quotas'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlatformDispatchConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(blank=True, null=True)),
                ('weekday', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('algorithm', models.CharField(choices=[('fifo', 'fifo'), ('newest', 'newest'), ('overdue', 'overdue'), ('persistence', 'persistence'), ('longest_idle', 'longest_idle'), ('low_rate_stores', 'low_rate_stores'), ('high_rate_stores', 'high_rate_stores'), ('high_value', 'high_value'), ('quick_wins', 'quick_wins'), ('balanced', 'balanced')], default='fifo', max_length=30)),
                ('wait_minutes', models.JSONField(default=platform_admin.dispatch_models.default_wait_minutes)),
                ('review_after', models.PositiveSmallIntegerField(default=4)),
                ('fail_after_review', models.PositiveSmallIntegerField(default=4)),
                ('max_open', models.PositiveSmallIntegerField(default=5)),
                ('weights', models.JSONField(blank=True, default=dict)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('store', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='dispatch_configs', to='stores.store')),
            ],
        ),
        migrations.CreateModel(
            name='PlatformOrderFlow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.CharField(choices=[('waiting', "En attente d'assignation"), ('assigned', 'Assignée'), ('failed', 'Échec'), ('done', 'Terminée')], db_index=True, default='waiting', max_length=10)),
                ('attempts', models.PositiveSmallIntegerField(default=0)),
                ('available_at', models.DateTimeField()),
                ('last_attempt_at', models.DateTimeField(blank=True, null=True)),
                ('admin_flagged_at', models.DateTimeField(blank=True, null=True)),
                ('failed_at', models.DateTimeField(blank=True, null=True)),
                ('done_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('confirmateur', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='flows', to='platform_admin.platformconfirmateur')),
                ('order', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='platform_flow', to='orders.order')),
            ],
        ),
        migrations.CreateModel(
            name='PlatformOrderEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('created', 'Commande entrée dans le flux'), ('assigned', 'Assignée à un confirmateur'), ('attempt', "Résultat d'appel"), ('requeued', "Remise en attente d'assignation"), ('escalated', "Signalée à l'admin"), ('failed', 'Échec définitif'), ('done', 'Terminée')], max_length=12)),
                ('outcome', models.CharField(blank=True, max_length=12)),
                ('note', models.CharField(blank=True, max_length=300)),
                ('detail', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('confirmateur', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='platform_admin.platformconfirmateur')),
                ('flow', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='platform_admin.platformorderflow')),
            ],
            options={
                'ordering': ['created_at', 'id'],
            },
        ),
    ]
