# Generated by Django 5.2.16 on 2026-08-12 22:00

import core.validators
import django.db.models.deletion
import inbox.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('orders', '0029_order_restocked_at'),
        ('stores', '0011_store_meta_description_store_meta_title_and_more'),
        ('team', '0003_teammemberpermission'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Conversation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('channel', models.CharField(choices=[('complaint', 'Réclamation'), ('exchange', 'Échange'), ('messenger', 'Messenger'), ('whatsapp', 'WhatsApp'), ('instagram', 'Instagram')], max_length=20)),
                ('subject', models.CharField(blank=True, max_length=200)),
                ('status', models.CharField(choices=[('open', 'Ouverte'), ('in_progress', 'En cours'), ('resolved', 'Résolue')], default='open', max_length=20)),
                ('customer_name', models.CharField(blank=True, max_length=200)),
                ('customer_phone', models.CharField(blank=True, max_length=30)),
                ('external_user_id', models.CharField(blank=True, help_text='Identifiant du client côté canal externe (PSID Messenger, numéro WhatsApp...)', max_length=100)),
                ('external_id', models.CharField(blank=True, help_text='Identifiant de la conversation côté canal externe', max_length=100)),
                ('assigned_at', models.DateTimeField(blank=True, null=True)),
                ('last_message_at', models.DateTimeField(blank=True, null=True)),
                ('last_customer_message_at', models.DateTimeField(blank=True, help_text='Sert la fenêtre de 24h imposée par Meta pour Messenger/WhatsApp — pas encore appliqué tant que ces canaux ne sont pas branchés', null=True)),
                ('unread_count', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assigned_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_conversations', to='team.teammember')),
                ('order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='conversations', to='orders.order')),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conversations', to='stores.store')),
            ],
            options={
                'ordering': ['-last_message_at', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('direction', models.CharField(choices=[('inbound', 'Entrant'), ('outbound', 'Sortant')], max_length=10)),
                ('body', models.TextField(blank=True)),
                ('status_change', models.CharField(blank=True, help_text='Renseigné si ce message accompagne un changement de statut (repris de ComplaintMessage.status)', max_length=20)),
                ('attachment', models.ImageField(blank=True, null=True, upload_to=inbox.models.conversation_attachment_path, validators=[core.validators.validate_image_extension, core.validators.validate_image_size])),
                ('external_id', models.CharField(blank=True, max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(blank=True, help_text='null = message du client', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('conversation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='inbox.conversation')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
    ]
