# Generated by Django 5.2.15 on 2026-07-02 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0002_storesettings'),
    ]

    operations = [
        migrations.AddField(
            model_name='storesettings',
            name='abandoned_cart_delay_hours',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
