# Generated by Django 5.2.15 on 2026-07-02 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0003_storesettings_abandoned_cart_delay_hours'),
    ]

    operations = [
        migrations.AddField(
            model_name='storesettings',
            name='theme_font',
            field=models.CharField(choices=[('inter', 'Inter'), ('poppins', 'Poppins'), ('cairo', 'Cairo')], default='inter', max_length=20),
        ),
        migrations.AddField(
            model_name='storesettings',
            name='theme_primary',
            field=models.CharField(blank=True, max_length=7),
        ),
        migrations.AddField(
            model_name='storesettings',
            name='theme_secondary',
            field=models.CharField(blank=True, max_length=7),
        ),
        migrations.AddField(
            model_name='storesettings',
            name='theme_template',
            field=models.CharField(choices=[('violet', 'Violet'), ('midnight', 'Midnight'), ('sahara', 'Sahara')], default='violet', max_length=20),
        ),
    ]
