# Generated by Django 5.2.15 on 2026-07-03 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0005_storesettings_menu_items_mediafolder_mediafile_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='storesettings',
            name='risk_period_days',
            field=models.PositiveIntegerField(default=90),
        ),
        migrations.AddField(
            model_name='storesettings',
            name='risk_threshold_orders',
            field=models.PositiveIntegerField(default=3),
        ),
    ]
