# Generated by Django 5.2.15 on 2026-07-03 17:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0006_storesettings_risk_period_days_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PixelConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pixel_type', models.CharField(choices=[('facebook', 'Facebook Pixel'), ('tiktok', 'TikTok Pixel'), ('google_analytics', 'Google Analytics'), ('google_tag_manager', 'Google Tag Manager')], max_length=30)),
                ('pixel_id', models.CharField(max_length=150)),
                ('label', models.CharField(blank=True, max_length=100)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pixels', to='stores.store')),
            ],
            options={
                'ordering': ['pixel_type', '-created_at'],
            },
        ),
    ]
