# Generated by Django 5.2.15 on 2026-07-03 18:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0007_pixelconfig'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubscriptionPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('orders_limit', models.PositiveIntegerField(blank=True, help_text='Vide = illimité', null=True)),
                ('price_monthly', models.DecimalField(decimal_places=2, max_digits=10)),
                ('price_yearly', models.DecimalField(decimal_places=2, max_digits=10)),
                ('features', models.JSONField(default=list, help_text='Liste de textes affichés sous le palier')),
                ('is_active', models.BooleanField(default=True)),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.AddField(
            model_name='subscriptionquota',
            name='billing_cycle',
            field=models.CharField(blank=True, choices=[('monthly', 'Mensuel'), ('yearly', 'Annuel')], max_length=10),
        ),
        migrations.AddField(
            model_name='subscriptionquota',
            name='period_end',
            field=models.DateTimeField(blank=True, help_text='Fin de la période payée en cours (abonnement actif seulement)', null=True),
        ),
        migrations.AddField(
            model_name='subscriptionquota',
            name='plan',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subscribers', to='stores.subscriptionplan'),
        ),
    ]
