# Generated by Django 5.2.15 on 2026-07-03 18:54

import core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0009_seed_subscription_plans'),
    ]

    operations = [
        migrations.AlterField(
            model_name='store',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='store_logos/', validators=[core.validators.validate_image_extension, core.validators.validate_image_size]),
        ),
    ]
