# Generated by Django 5.2.16 on 2026-08-07 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0010_alter_store_logo'),
    ]

    operations = [
        migrations.AddField(
            model_name='store',
            name='meta_description',
            field=models.CharField(blank=True, help_text='Balise <meta name="description"> de la page d\'accueil — retombe sur la description si vide', max_length=160),
        ),
        migrations.AddField(
            model_name='store',
            name='meta_title',
            field=models.CharField(blank=True, help_text="Balise <title> de la page d'accueil publique — retombe sur le nom de la boutique si vide", max_length=70),
        ),
        migrations.AddField(
            model_name='storepage',
            name='meta_description',
            field=models.CharField(blank=True, help_text='Balise <meta name="description"> — retombe sur un extrait du contenu si vide', max_length=160),
        ),
        migrations.AddField(
            model_name='storepage',
            name='meta_title',
            field=models.CharField(blank=True, help_text='Balise <title> de la page publique — retombe sur le titre si vide', max_length=70),
        ),
    ]
