# Generated by Django 5.2.16 on 2026-08-13 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0011_store_meta_description_store_meta_title_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='storesettings',
            name='insurance_fee',
            field=models.DecimalField(decimal_places=2, default=200, help_text='Supplément ajouté aux frais de livraison quand le type "Assurance" est choisi sur une commande', max_digits=10),
        ),
    ]
