# Generated by Django 5.2.16 on 2026-08-13 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0012_storesettings_insurance_fee'),
    ]

    operations = [
        migrations.AddField(
            model_name='store',
            name='currency',
            field=models.CharField(default='DZD', max_length=3),
        ),
        migrations.AddField(
            model_name='store',
            name='currency_symbol',
            field=models.CharField(default='DA', max_length=5),
        ),
        migrations.AddField(
            model_name='store',
            name='facebook_url',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='store',
            name='instagram_url',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='store',
            name='tiktok_url',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='store',
            name='twitter_url',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='storesettings',
            name='deduct_stock_on_order_create',
            field=models.BooleanField(default=True, help_text="Si désactivé, le stock n'est décrémenté qu'à la confirmation de la commande plutôt qu'à sa création"),
        ),
        migrations.AddField(
            model_name='storesettings',
            name='free_shipping_if_product_free_shipping',
            field=models.BooleanField(default=False, help_text='Livraison offerte sur tout le panier si au moins un article a Product.free_shipping=True'),
        ),
        migrations.AddField(
            model_name='storesettings',
            name='max_order_amount',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Montant maximum accepté pour une commande sur la boutique publique (vide = pas de limite)', max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='storesettings',
            name='max_order_quantity',
            field=models.PositiveIntegerField(blank=True, help_text="Quantité totale maximum d'articles pour une commande sur la boutique publique (vide = pas de limite)", null=True),
        ),
        migrations.AddField(
            model_name='storesettings',
            name='notify_duplicate_orders',
            field=models.BooleanField(default=True, help_text='Notifie (webhook order.duplicate_detected) quand une commande arrive avec un téléphone déjà présent récemment'),
        ),
        migrations.AddField(
            model_name='storesettings',
            name='notify_new_orders',
            field=models.BooleanField(default=True, help_text='Affiche le badge/compteur de nouvelles commandes dans le tableau de bord'),
        ),
        migrations.AddField(
            model_name='storesettings',
            name='order_confirmed_otp_enabled',
            field=models.BooleanField(default=False, help_text="Désactivé tant qu'aucun fournisseur SMS n'est configuré (TBD)"),
        ),
        migrations.AddField(
            model_name='storesettings',
            name='order_prefix',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='storesettings',
            name='order_suffix',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='storesettings',
            name='sms_api_token',
            field=models.CharField(blank=True, help_text="Jeton du futur fournisseur SMS — stocké pour quand l'intégration sera branchée", max_length=200),
        ),
        migrations.AddField(
            model_name='storesettings',
            name='sms_notifications_enabled',
            field=models.BooleanField(default=False, help_text="Désactivé tant qu'aucun fournisseur SMS n'est configuré (TBD)"),
        ),
    ]
