# Generated by Django 5.2.16 on 2026-08-13 21:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0013_store_currency_store_currency_symbol_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pixelconfig',
            name='access_token',
            field=models.CharField(blank=True, help_text="Jeton d'accès Conversions API (Facebook) / Events API (TikTok) — envoi d'évènements serveur, en plus du script client", max_length=500),
        ),
        migrations.AddField(
            model_name='pixelconfig',
            name='domain_verification',
            field=models.CharField(blank=True, help_text='Balise meta de vérification de domaine Facebook Business (facebook-domain-verification)', max_length=200),
        ),
        migrations.AddField(
            model_name='pixelconfig',
            name='ga_service_account_json',
            field=models.TextField(blank=True, help_text="JSON du compte de service Google (accès API GA4) — non utilisé pour l'instant, stocké pour une future intégration serveur"),
        ),
        migrations.AddField(
            model_name='pixelconfig',
            name='ga_view_id',
            field=models.CharField(blank=True, help_text='Identifiant de propriété/vue GA4', max_length=100),
        ),
        migrations.AlterField(
            model_name='pixelconfig',
            name='pixel_id',
            field=models.CharField(help_text='Identifiant du pixel (Facebook/TikTok) ou ID de mesure GA4 (G-XXXXXXXXXX)', max_length=150),
        ),
    ]
