# Generated by Django 5.2.16 on 2026-08-13 21:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0014_pixelconfig_access_token_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pixelconfig',
            name='ga_api_secret',
            field=models.CharField(blank=True, help_text="Secret API du Measurement Protocol GA4 (Admin GA4 → Flux de données → Measurement Protocol) — utilisé pour l'envoi réel de l'évènement purchase", max_length=200),
        ),
        migrations.AlterField(
            model_name='pixelconfig',
            name='ga_service_account_json',
            field=models.TextField(blank=True, help_text="JSON du compte de service Google (API Analytics Admin/Data, lecture de rapports) — non utilisé pour l'instant, stocké pour une future intégration"),
        ),
    ]
