# Generated by Django 5.2.16 on 2026-08-14 11:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0015_pixelconfig_ga_api_secret_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='storesettings',
            name='free_shipping_if_product_free_shipping',
        ),
    ]
