# Generated by Django 5.2.16 on 2026-09-04 14:55

import core.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0016_remove_storesettings_free_shipping_if_product_free_shipping'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pixelconfig',
            name='access_token',
            field=core.fields.EncryptedTextField(blank=True, help_text="Jeton d'accès Conversions API (Facebook) / Events API (TikTok) — envoi d'évènements serveur, en plus du script client"),
        ),
        migrations.AlterField(
            model_name='pixelconfig',
            name='ga_api_secret',
            field=core.fields.EncryptedTextField(blank=True, help_text="Secret API du Measurement Protocol GA4 (Admin GA4 → Flux de données → Measurement Protocol) — utilisé pour l'envoi réel de l'évènement purchase"),
        ),
        migrations.AlterField(
            model_name='pixelconfig',
            name='ga_service_account_json',
            field=core.fields.EncryptedTextField(blank=True, help_text="JSON du compte de service Google (API Analytics Admin/Data, lecture de rapports) — non utilisé pour l'instant, stocké pour une future intégration"),
        ),
    ]
