# Generated by Django 5.2.17 on 2026-09-11 12:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0018_encrypt_existing_secrets'),
    ]

    operations = [
        migrations.CreateModel(
            name='StoreAudit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('computed_at', models.DateTimeField(auto_now=True)),
                ('global_score', models.PositiveSmallIntegerField(null=True)),
                ('catalogue_score', models.PositiveSmallIntegerField(null=True)),
                ('logistics_score', models.PositiveSmallIntegerField(null=True)),
                ('stock_score', models.PositiveSmallIntegerField(null=True)),
                ('returns_risk_score', models.PositiveSmallIntegerField(null=True)),
                ('details', models.JSONField(default=dict)),
                ('synthesis', models.TextField(blank=True)),
                ('store', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='audit', to='stores.store')),
            ],
        ),
    ]
