# Generated by Django 5.2.17 on 2026-10-04 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0020_subscriptionpayment'),
    ]

    operations = [
        migrations.AddField(
            model_name='store',
            name='suspended_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='store',
            name='suspension_reason',
            field=models.TextField(blank=True),
        ),
    ]
