# Generated by Django 5.2.17 on 2026-10-04 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0021_suspension_and_platform_audit'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscriptionpayment',
            name='refund_reason',
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AddField(
            model_name='subscriptionpayment',
            name='refunded_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='subscriptionpayment',
            name='status',
            field=models.CharField(choices=[('pending', 'En attente'), ('success', 'Payé'), ('failed', 'Échoué'), ('refunded', 'Remboursé')], default='pending', max_length=10),
        ),
    ]
