# Generated by Django 5.2.17 on 2026-10-05 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0022_subscriptionpayment_refund'),
    ]

    operations = [
        migrations.AddField(
            model_name='store',
            name='disabled_features',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
