# Generated by Django 5.2.17 on 2026-10-05 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0024_invoices'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscriptionplan',
            name='ai_daily_limit',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='subscriptionplan',
            name='ai_weekly_limit',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
