# Generated by Django 5.2.17 on 2026-10-05 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0025_ai_limits'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscriptionplan',
            name='ai_quotas',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
