# Generated by Django 5.2.15 on 2026-07-03 17:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0006_storesettings_risk_period_days_and_more'),
        ('team', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RolePermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('admin', 'admin'), ('confirmateur', 'confirmateur'), ('dropshipper', 'dropshipper')], max_length=20)),
                ('permission', models.CharField(max_length=50)),
                ('enabled', models.BooleanField(default=True)),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='role_permissions', to='stores.store')),
            ],
            options={
                'unique_together': {('store', 'role', 'permission')},
            },
        ),
    ]
