# Generated by Django 5.2.15 on 2026-07-07 21:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0002_rolepermission'),
    ]

    operations = [
        migrations.CreateModel(
            name='TeamMemberPermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('permission', models.CharField(max_length=50)),
                ('enabled', models.BooleanField(default=True)),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='permission_overrides', to='team.teammember')),
            ],
            options={
                'unique_together': {('member', 'permission')},
            },
        ),
    ]
