# Generated by Django 5.2.16 on 2026-08-17 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0003_teammemberpermission'),
    ]

    operations = [
        migrations.AddField(
            model_name='teammember',
            name='is_online',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='teammember',
            name='last_seen_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
