# Generated by Django 5.2.15 on 2026-07-03 18:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('stores', '0007_pixelconfig'),
    ]

    operations = [
        migrations.CreateModel(
            name='IncomingWebhookKey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(blank=True, max_length=64, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('store', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='incoming_webhook_key', to='stores.store')),
            ],
        ),
        migrations.CreateModel(
            name='WebhookEndpoint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100)),
                ('url', models.URLField(max_length=500)),
                ('events', models.JSONField(default=list, help_text='Liste de clés WEBHOOK_EVENT_CHOICES — vide = tous les événements')),
                ('secret', models.CharField(blank=True, max_length=64)),
                ('is_active', models.BooleanField(default=True)),
                ('consecutive_failures', models.PositiveIntegerField(default=0)),
                ('last_triggered_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='webhook_endpoints', to='stores.store')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='WebhookLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('direction', models.CharField(choices=[('outbound', 'Sortant'), ('inbound', 'Entrant')], max_length=10)),
                ('event', models.CharField(blank=True, max_length=50)),
                ('payload', models.JSONField(default=dict)),
                ('status_code', models.PositiveIntegerField(blank=True, null=True)),
                ('status', models.CharField(choices=[('success', 'Succès'), ('error', 'Erreur')], max_length=10)),
                ('message', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('endpoint', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='logs', to='webhooks.webhookendpoint')),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='webhook_logs', to='stores.store')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
