# Generated by Django 5.2.16 on 2026-09-04 14:55

import core.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webhooks', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='webhookendpoint',
            name='secret',
            field=core.fields.EncryptedTextField(blank=True),
        ),
    ]
