# Generated by Django 5.2.16 on 2026-08-17 10:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('stores', '0016_remove_storesettings_free_shipping_if_product_free_shipping'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('actor_name', models.CharField(blank=True, max_length=200)),
                ('actor_role', models.CharField(blank=True, max_length=20)),
                ('action', models.CharField(max_length=60)),
                ('target_type', models.CharField(blank=True, max_length=40)),
                ('target_id', models.IntegerField(blank=True, null=True)),
                ('target_repr', models.CharField(blank=True, max_length=200)),
                ('description', models.TextField(blank=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to=settings.AUTH_USER_MODEL)),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audit_logs', to='stores.store')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['store', '-created_at'], name='audit_audit_store_i_ce34da_idx'), models.Index(fields=['store', 'action'], name='audit_audit_store_i_53c412_idx'), models.Index(fields=['store', 'target_type', 'target_id'], name='audit_audit_store_i_49f9f7_idx')],
            },
        ),
    ]
