# Generated by Django 5.2.17 on 2026-10-04 20:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audit', '0001_initial'),
        ('stores', '0021_suspension_and_platform_audit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auditlog',
            name='store',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='audit_logs', to='stores.store'),
        ),
    ]
